Repository jackwish/tflite2onnx, pull requests merged in 2021-01, with the labels that each got.

#48 Op: Squared difference
  assets/tests/squared-diff.float32.tflite
  tests/test_ops.py
  tflite2onnx/op/__init__.py
  tflite2onnx/op/squared_difference.py
Labels: Operator

#52 Quant: fold FP16 tensors into FP32
  assets/tests/conv-quant-fp16.float32.tflite
  tests/test_ops.py
  tflite2onnx/graph.py
  tflite2onnx/quantize.py
Labels: Enhancement, Quantization

#59 drop setup.py and fix CI
  .codecov.yaml
  .github/workflows/build.yaml
  .github/workflows/publish.yml
  README.md
  requirements.txt
  scripts/build-wheel.sh
  setup.cfg
  setup.py
  tflite2onnx/__init__.py
  tflite2onnx/convert.py
Labels: CI
